Nager.AmazonProductAdvertising.Website/Controllers/AmazonController.cs
using Nager.AmazonProductAdvertising.Model;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;

namespace Nager.AmazonProductAdvertising.Website.Controllers
{
    public class AmazonController : Controller
    {
        private const string AssociateTag = "nager-20";

        private AmazonAuthentication GetConfig()
        {
            var accessKey = ConfigurationManager.AppSettings["AmazonAccessKey"];
            var secretKey = ConfigurationManager.AppSettings["AmazonSecretKey"];

            var authentication = new AmazonAuthentication();
            authentication.AccessKey = accessKey;
            authentication.SecretKey = secretKey;

            return authentication;
        }

        public ActionResult Lookup(string articleNumber)
        {
            if (string.IsNullOrEmpty(articleNumber))
            {
                return View();
            }

            var authentication = this.GetConfig();

            var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, AssociateTag);
            var result = wrapper.Lookup(articleNumber.Trim());

            return View(result);
        }

        public ActionResult Lookups(string[] articleNumbers)
        {
            if (articleNumbers == null)
            {
                return View();
            }

            var authentication = this.GetConfig();

            var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, AssociateTag);
            var result = wrapper.Lookup(articleNumbers);

            return View("Lookup", result);
        }

        public ActionResult Search(string search)
        {
            if (string.IsNullOrEmpty(search))
            {
                return View();
            }

            ViewBag.Search = search.Trim();

            var authentication = this.GetConfig();

            var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, AssociateTag);
            var responseGroup = AmazonResponseGroup.ItemAttributes | AmazonResponseGroup.Images;

            var result = wrapper.Search(search.Trim(), AmazonSearchIndex.All, responseGroup);

            return View(result);
        }

        public ActionResult Detail(string articleNumber)
        {
            if (string.IsNullOrEmpty(articleNumber))
            {
                return View();
            }

            var authentication = this.GetConfig();

            var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, AssociateTag);
            var result = wrapper.Lookup(articleNumber.Trim());

            var item = result.Items?.Item.FirstOrDefault();

            return View(item);
        }
    }
}

Nager.AmazonProductAdvertising.Website/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Nager.AmazonProductAdvertising.Website.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Nager.AmazonProductAdvertising.Website/Views/Amazon/Detail.cshtml
@model Nager.AmazonProductAdvertising.Model.Item
@{
    ViewBag.Title = $"{Model.ItemAttributes.Title} {Model.ASIN}";
}

<div class="row">
    <div class="col-xs-12">
        <div class="row">
            <div class="col-xs-12">
                <h3>@Model.ItemAttributes.Title <small>@Model.ASIN</small></h3>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4">
                @if (Model.LargeImage != null)
                {
                    <img src="@Model.LargeImage.URL" alt="@Model.ItemAttributes.Title" class="img-thumbnail" />
                }
                @if (Model.ItemAttributes.Feature != null)
                {
                    <h4>Features</h4>
                    <ul class="list-group">
                        @foreach (var feature in Model.ItemAttributes.Feature)
                        {
                            <li class="list-group-item">@feature</li>
                        }
                    </ul>
                }
            </div>
            <div class="col-xs-12 col-sm-6 col-md-8">

                <h3>@(Model.OfferSummary?.LowestNewPrice?.FormattedPrice)</h3>
                <a class="btn btn-primary btn-lg" href="@Model.DetailPageURL" role="button">Buy at Amazon</a><br />
                <br />
                @if (Model.EditorialReviews != null)
                {
                    <span>@Html.Raw(Model.EditorialReviews?.Where(o => o.Source == "Product Description").Select(o => o.Content).FirstOrDefault())</span>
                }
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-xs-12 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Product Details</h3>
                    </div>
                    <div class="panel-body">
                        <table class="table">
                            @if (!String.IsNullOrEmpty(Model.ItemAttributes.Manufacturer))
                            {
                                <tr>
                                    <th>Manufacturer</th>
                                    <td>@Model.ItemAttributes.Manufacturer</td>
                                </tr>
                            }
                            @if (!String.IsNullOrEmpty(Model.ItemAttributes.Model))
                            {
                                <tr>
                                    <th>Model</th>
                                    <td>@Model.ItemAttributes.Model</td>
                                </tr>
                            }
                            @if (!String.IsNullOrEmpty(Model.ItemAttributes.ModelYear))
                            {
                                <tr>
                                    <th>ModelYear</th>
                                    <td>@Model.ItemAttributes.ModelYear</td>
                                </tr>
                            }
                            @if (!String.IsNullOrEmpty(Model.ItemAttributes.Color))
                            {
                                <tr>
                                    <th>Color</th>
                                    <td>@Model.ItemAttributes.Color</td>
                                </tr>
                            }
                            @if (!String.IsNullOrEmpty(Model.ItemAttributes.ItemPartNumber))
                            {
                                <tr>
                                    <th>ItemPartNumber</th>
                                    <td>@Model.ItemAttributes.ItemPartNumber</td>
                                </tr>
                            }
                            @if (!String.IsNullOrEmpty(Model.ItemAttributes.EAN))
                            {
                                <tr>
                                    <th>EAN</th>
                                    <td>@Model.ItemAttributes.EAN</td>
                                </tr>
                            }
                            @if (!String.IsNullOrEmpty(Model.ItemAttributes.ProductGroup))
                            {
                                <tr>
                                    <th>ProductGroup</th>
                                    <td>@Model.ItemAttributes.ProductGroup</td>
                                </tr>
                            }
                            @if (!String.IsNullOrEmpty(Model.ItemAttributes.PublicationDate))
                            {
                                <tr>
                                    <th>PublicationDate</th>
                                    <td>@Model.ItemAttributes.PublicationDate</td>
                                </tr>
                            }
                            @if (!String.IsNullOrEmpty(Model.ItemAttributes.ReleaseDate))
                            {
                                <tr>
                                    <th>ReleaseDate</th>
                                    <td>@Model.ItemAttributes.ReleaseDate</td>
                                </tr>
                            }
                            @if (!String.IsNullOrEmpty(Model.ItemAttributes.Warranty))
                            {
                                <tr>
                                    <th>Warranty</th>
                                    <td>@Model.ItemAttributes.Warranty</td>
                                </tr>
                            }
                            @if (!String.IsNullOrEmpty(Model.ItemAttributes.LegalDisclaimer))
                            {
                                <tr>
                                    <th>LegalDisclaimer</th>
                                    <td>@Model.ItemAttributes.LegalDisclaimer</td>
                                </tr>
                            }
                            @if (!String.IsNullOrEmpty(@Model.SalesRank))
                            {
                                <tr>
                                    <th>SalesRank</th>
                                    <td><span class="glyphicon glyphicon-star" style="color:#ffd800; font-size:15px;" aria-hidden="true"></span> @Model.SalesRank</td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>

                @if (Model.SimilarProducts != null)
                {
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Similar Products</h3>
                    </div>
                    <div class="panel-body">
                        <ul class="list-group">
                            @foreach (var product in Model.SimilarProducts)
                            {
                                <li class="list-group-item"><a href="/Amazon/Detail?articleNumber=@product.ASIN">@product.Title</a></li>
                            }
                        </ul>
                    </div>
                </div>
                }


            </div>
            @if (Model.ImageSets != null)
            {
            <div class="col-xs-12 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Gallery</h3>
                    </div>
                    <div class="panel-body">
                        <div id="slideimages" class="carousel slide" data-ride="carousel">
                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox">
                                @{
                                    var myClass = "active";
                                    foreach (var image in Model.ImageSets.OrderByDescending(o => o.Category == "primary"))
                                    {
                                        <div class="item @myClass">
                                            <img src="@image.LargeImage.URL" alt="@Model.ItemAttributes.Title" style="text-align:center;" />
                                        </div>
                                        myClass = "";
                                    }
                                }
                            </div>

                            <!-- Controls -->
                            <a class="left carousel-control" href="#slideimages" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#slideimages" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>

Nager.AmazonProductAdvertising.Website/Views/Amazon/Lookup.cshtml
@model Nager.AmazonProductAdvertising.Model.AmazonItemResponse
@{
    ViewBag.Title = "Lookup";
}

<h2>Lookup</h2>

<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-inline">
            <div class="form-group">
                <label for="search">Lookup</label>
                <input type="text" class="form-control" id="lookup" name="articleNumber" placeholder="articleNumber">
            </div>
            <button type="submit" class="btn btn-primary">Lookup</button>
        </form>
    </div>
</div>

<div class="row">
    @if (Model != null)
    {
        if (Model.Items.Request.Errors?.Length > 0)
        {
            foreach (var error in Model.Items.Request.Errors)
            {
                <div class="alert alert-danger" role="alert"><strong>@error.Code</strong><br />@error.Message</div>
            }
        }

        if (Model.Items.Item != null)
        {
            foreach (var item in Model.Items.Item)
            {
                @Html.Partial("_ItemOverview", item)
            }
        }
    }
</div>

Nager.AmazonProductAdvertising.Website/Views/Amazon/Search.cshtml
@model Nager.AmazonProductAdvertising.Model.AmazonItemResponse
@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<div class="panel panel-default">
    <div class="panel-body">
        @using (Html.BeginForm("Search", "Amazon", FormMethod.Get, new { Class = "form-inline" }))
        {
            <div class="form-group">
                <label for="search">Search</label>
                <input type="text" class="form-control" id="search" name="search" placeholder="search" value="@ViewBag.Search">
            </div>
            <button type="submit" class="btn btn-primary">Search</button>
        }
    </div>
</div>

<div class="row">
    @if (Model != null)
    {
        if (Model.Items != null && Model.Items.Item != null)
        {
            foreach (var item in Model.Items.Item)
            {
                @Html.Partial("_ItemOverview", item)
            }
        }
    }
</div>

Nager.AmazonProductAdvertising.Website/Views/Amazon/_ItemOverview.cshtml
@model Nager.AmazonProductAdvertising.Model.Item
<div class="col-xs-12 col-sm-6 col-md-4" style="min-height:250px;">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="thumbnail">
                @if (Model.MediumImage != null)
                {
                    <a href="/Amazon/Detail?articleNumber=@Model.ASIN"><img src="@Model.MediumImage.URL" alt="@Model.ItemAttributes.Title" border="0" /></a>
                }
                <div class="caption">
                    <span>ASIN: @Model.ASIN</span>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6">
            <h5>@Model.ItemAttributes.Title</h5>
            <h3>@(Model.OfferSummary?.LowestNewPrice?.FormattedPrice)</h3>
            @Html.ActionLink("Details", "Detail", "Amazon", new { articleNumber = Model.ASIN }, new { Class = "btn btn-primary" })
        </div>
    </div>
    <div class="hidden-sm hidden-md hidden-lg"><hr /></div>
</div>

Nager.AmazonProductAdvertising.Website/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<h2>Search</h2>

<div class="panel panel-default">
    <div class="panel-body">
        @using(Html.BeginForm("Search", "Amazon", FormMethod.Get, new { Class = "form-inline" }))
        {
            <div class="form-group">
                <input type="text" class="form-control" id="search" name="search" placeholder="search">
            </div>
            <button type="submit" class="btn btn-primary">Search</button>
        }
    </div>
</div>

<div class="product-groups">
    <div class="col-xs-12 col-sm-12 col-md-6 list-group">
        <a class="list-group-item" href="/Amazon/Lookups/?articleNumbers=B014OWGRQU&articleNumbers=B01IK9GEQG&articleNumbers=B009OVGKTQ&articleNumbers=B018JO5BRK&articleNumbers=B00ALNJN72&articleNumbers=B01LYYC4MW"><i class="fa fa-wifi fa-fw fa-5x" aria-hidden="true"></i>&nbsp; <span><h4>ESP8266</h4>Ultra-low-Power-32-Bit-Microcontroller with WLAN</span></a>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 list-group">
        <a class="list-group-item" href="/Amazon/Lookups/?articleNumbers=B01FU5Z6JO&articleNumbers=B01BHIBGBA&articleNumbers=B015OHXQAO&articleNumbers=B0157G4GEM&articleNumbers=B01MRFE0HZ"><i class="fa fa-bicycle fa-fw fa-5x" aria-hidden="true"></i>&nbsp; <span><h4>E-Bike</h4>Battery powered bike</span></a>
    </div>
    <div class="col-xs-12 col-sm-6 list-group">
        <a class="list-group-item" href="/Amazon/Search/?search=car"><i class="fa fa-car fa-fw fa-5x" aria-hidden="true"></i>&nbsp; Car</a>
        <a class="list-group-item" href="/Amazon/Search/?search=bike"><i class="fa fa-bicycle fa-fw fa-5x" aria-hidden="true"></i>&nbsp; Bike</a>
    </div>
    <div class="col-xs-12 col-sm-6 list-group">
        <a class="list-group-item" href="/Amazon/Search/?search=diamond"><i class="fa fa-diamond fa-fw fa-5x" aria-hidden="true"></i>&nbsp; Diamond</a>
        <a class="list-group-item" href="/Amazon/Search/?search=coffee"><i class="fa fa-coffee fa-fw fa-5x" aria-hidden="true"></i>&nbsp; Coffee</a>
    </div>
    <div class="col-xs-12 col-sm-6 list-group">
        <a class="list-group-item" href="/Amazon/Search/?search=battery"><i class="fa fa-battery-3 fa-fw fa-5x" aria-hidden="true"></i>&nbsp; Battery</a>
        <a class="list-group-item" href="/Amazon/Search/?search=beer"><i class="fa fa-beer fa-fw fa-5x" aria-hidden="true"></i>&nbsp; Beer</a>
    </div>
    <div class="col-xs-12 col-sm-6 list-group">
        <a class="list-group-item" href="/Amazon/Search/?search=spyglass"><i class="fa fa-binoculars fa-fw fa-5x" aria-hidden="true"></i>&nbsp; Spy glass</a>
        <a class="list-group-item" href="/Amazon/Search/?search=calculator"><i class="fa fa-calculator fa-fw fa-5x" aria-hidden="true"></i>&nbsp; Calculator</a>
    </div>
</div>

Nager.AmazonProductAdvertising.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nager.AmazonProductAdvertising</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NAGER SHOP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Lookup", "Lookup", "Amazon")</li>
                    <li>@Html.ActionLink("Search", "Search", "Amazon")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <a href="https://github.com/tinohager/Nager.AmazonProductAdvertising">Nager.AmazonProductAdvertising</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>